# -*- coding: utf-8 -*-
"""primeiro-codigo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ec0qxM5-u5nkXDjxCfbbI4l7gL05g_Ei
"""

print("hello")